import type { Metadata } from "next";
import { Barlow, Fraunces } from "next/font/google";
import "./globals.css";

const barlow = Barlow({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-barlow",
    weight: ["600"],
    style: ["normal", "italic"],
});

const fraunces = Fraunces({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-fraunces",
    weight: ["700", "900"],
    style: ["normal", "italic"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${barlow.variable} ${fraunces.variable}`}>
                {children}
            </body>
        </html>
    );
}
